export class ScenePackageClient {
  constructor(base=""){this.base=base.replace(/\/$/,"")}
  async request(path,options={}){const response=await fetch(`${this.base}${path}`,options);if(!response.ok){const body=await response.json().catch(()=>({}));const error=new Error(body.detail||`Request failed (${response.status})`);error.status=response.status;throw error}return response.json()}
  getScene(sceneId){return this.request(`/api/scenes/${encodeURIComponent(sceneId)}`)}
  updateLabel(scene,object,label){return this.request(`/api/scenes/${encodeURIComponent(scene.scene_id)}/objects/${object.object_id}/label`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({semantic_label:label,expected_package_revision:scene.package_revision,expected_object_version:object.version})})}
  updateApproval(scene,object,status){return this.request(`/api/scenes/${encodeURIComponent(scene.scene_id)}/objects/${object.object_id}/approval`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({approval_status:status,expected_package_revision:scene.package_revision,expected_object_version:object.version})})}
  history(sceneId,objectId){return this.request(`/api/scenes/${encodeURIComponent(sceneId)}/objects/${objectId}/mask-revisions`)}
  saveRevision(scene,object,maskBlob,delta,author="mask-review-ui"){const form=new FormData();form.append("resulting_mask",maskBlob,"mask.png");form.append("edit_delta",new Blob([JSON.stringify(delta)],{type:"application/json"}),"delta.json");form.append("expected_package_revision",scene.package_revision);form.append("expected_object_version",object.version);form.append("expected_mask_revision",object.mask_revision);form.append("author",author);form.append("operation","manual");return this.request(`/api/scenes/${encodeURIComponent(scene.scene_id)}/objects/${object.object_id}/mask-revisions`,{method:"POST",body:form})}
  updateTransform(scene,object,transform){return this.request(`/api/scenes/${encodeURIComponent(scene.scene_id)}/scene-manifest`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_package_revision:scene.package_revision,transforms:[{object_id:object.object_id,expected_object_version:object.version,expected_mask_revision:object.mask_revision,transform,blender_object_identifier:object.blender_object_identifier??`sam_${object.object_id}`}]})})}
}
