export const SYNC_SCHEMA_VERSION="1.0.0";
export class BlenderSyncError extends Error{constructor(message,{code="sync_failed",details={},status=0}={}){super(message);this.name="BlenderSyncError";this.code=code;this.details=details;this.status=status}}
export function findDuplicateIds(scene){const ids=[...(scene.structural_room_proxies??[]).map(o=>o.proxy_id),...(scene.semantic_objects??[]).map(o=>o.object_id)];return[...new Set(ids.filter((id,index)=>ids.indexOf(id)!==index))].sort()}
export function staleObjectIds(scene){const revisions=new Map((scene.mask_revisions??[]).map(r=>[r.revision_id,r]));return(scene.semantic_objects??[]).filter(o=>["invalidated","recompute_required"].includes(revisions.get(o.mask_revision)?.geometry_invalidation_status)).map(o=>o.object_id)}
export function sceneForSync(scene){return{schema_version:scene.schema_version,package_revision:scene.package_revision,scene_id:scene.scene_id,structural_room_proxies:scene.structural_room_proxies,semantic_objects:scene.semantic_objects.map(({object_id,version,semantic_label,display_name,mask_revision,center,dimensions,quaternion})=>({object_id,version,semantic_label,display_name,mask_revision,center,dimensions,quaternion}))}}
export class BlenderSyncClient extends EventTarget{
  constructor({base="http://127.0.0.1:8765",fetchImpl=globalThis.fetch,pollInterval=700,timer=globalThis}={}){super();this.base=base.replace(/\/$/,"");this.fetch=fetchImpl;this.pollInterval=pollInterval;this.timer=timer;this.sequence=0;this.pollHandle=null;this.status="disconnected";this.scene=null}
  envelope(type,{scene=this.scene,object=null,payload={}}={}){return{schema_version:SYNC_SCHEMA_VERSION,message_id:globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`,type,scene_id:scene?.scene_id??null,object_id:object?.object_id??null,revision:scene?.package_revision??null,payload}}
  setStatus(status,detail=""){this.status=status;this.dispatchEvent(new CustomEvent("status",{detail:{status,detail}}))}
  async command(type,context={}){const message=this.envelope(type,context);let response;try{response=await this.fetch(`${this.base}/command`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(message)})}catch(error){throw new BlenderSyncError("Blender is not reachable",{code:"disconnected",details:{cause:String(error)}})}const body=await response.json().catch(()=>({}));if(!response.ok||body.type==="error"){const payload=body.payload??{};throw new BlenderSyncError(payload.message??`Blender synchronization failed (${response.status})`,{code:payload.code??"sync_failed",details:payload.details??{},status:response.status})}return body}
  async connect(scene){this.scene=scene;this.setStatus("connecting");try{const duplicates=findDuplicateIds(scene);if(duplicates.length)throw new BlenderSyncError("Scene contains duplicate semantic IDs",{code:"duplicate_semantic_id",details:{object_ids:duplicates}});await this.command("handshake",{scene});const result=await this.sync(scene);this.setStatus(staleObjectIds(scene).length?"stale":"synchronized");this.startPolling();return result}catch(error){this.setStatus("error",error.message);throw error}}
  async sync(scene=this.scene){this.scene=scene;const result=await this.command("scene_sync",{scene,payload:{scene_package:sceneForSync(scene),stale_object_ids:staleObjectIds(scene)}});this.setStatus(staleObjectIds(scene).length?"stale":"synchronized");return result}
  async select(object){if(!this.scene)return null;return this.command("select_highlight",{scene:this.scene,object,payload:{mask_revision:object.mask_revision}})}
  async acknowledge(event,payload={}){return this.command("sync_ack",{scene:this.scene,object:event.object_id?{object_id:event.object_id}:null,payload:{event_message_id:event.message_id,...payload}})}
  startPolling(){if(this.pollHandle!==null)return;const poll=async()=>{try{const response=await this.fetch(`${this.base}/events?since=${this.sequence}`,{cache:"no-store"});if(!response.ok)throw new Error(`event poll failed (${response.status})`);const body=await response.json();this.sequence=Math.max(this.sequence,body.latest_sequence??0);for(const event of body.events??[])this.dispatchEvent(new CustomEvent(event.type,{detail:event}));if(this.status==="error")this.setStatus("synchronized")}catch(error){this.setStatus("error",String(error.message??error))}};this.pollHandle=this.timer.setInterval(poll,this.pollInterval);poll()}
  disconnect(){if(this.pollHandle!==null)this.timer.clearInterval(this.pollHandle);this.pollHandle=null;this.scene=null;this.setStatus("disconnected")}
}
